services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    restart: always
    ports:
      - 8888:8888
    develop:
      watch:
        - action: sync
          path: .
          target: /app
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    user: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 5
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '16gb'
    environment:
      OLLAMA_DEBUG: 1
      OLLAMA_HOST: "0.0.0.0"
      OLLAMA_ORIGINS: "*"
    volumes:
      - ollama:/root/.ollama
    ports:
      - 31415:11434
volumes:
  ollama:
  db-data:
